Rails.application.config.assets.precompile += %w( profissionais.css )
Rails.application.config.assets.precompile += %w( profissionais_buscas.js )
Rails.application.config.assets.precompile += %w( profissionais.js )
Rails.application.config.assets.precompile += %w( servicos.css )
Rails.application.config.assets.precompile += %w( registros_servicos_realizados.js )
Rails.application.config.assets.precompile += %w( autocomplete-rails.js )