
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: projeto_e_profissional
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  schema_search_path: projeto_e_profissional



test:
  <<: *default
  database: projeto_e_profissional_test


production:
  <<: *default
  database: projeto_e_profissional_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432